# Generated by Django 4.1.6 on 2023-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_change', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
